# Generated by Django 5.1 on 2024-09-06 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='YouTubeAPISearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_query', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('location_radius', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('min_subscribers', models.IntegerField()),
                ('max_results', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='YouTubeAPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_id', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('link', models.URLField()),
                ('language', models.CharField(default='Not Specified', max_length=100)),
                ('subscribers', models.IntegerField()),
                ('description', models.TextField()),
                ('location', models.CharField(default='Not Specified', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('search', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ytsearchapi.youtubeapisearch')),
            ],
        ),
    ]
